name: homecoming
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  http: any
  http_parser: ^4.0.2
  path: ^1.9.0
  universal_html: ^2.2.4
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.0
  provider: ^6.1.2
  dio: ^5.7.0
  path_provider: ^2.1.4
  pdf: ^3.11.1
  printing: ^5.13.2
  open_file: ^3.5.3
  file_picker: ^8.1.2
  firebase_messaging: ^15.1.1
  firebase_core: ^3.4.1


dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/
    - assets/imagenes/fotos_mascotas/
    - assets/imagenes/perro.png
    - assets/imagenes/gato.png
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
