name: homecoming
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.0 # Asegúrate de usar la versión más reciente
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  http: any
  http_parser: ^4.0.0
  path: ^1.8.2 # Añade esta dependencia
  universal_html: ^2.0.5
  google_maps_flutter: ^2.1.3
  url_launcher: ^6.0.9  # Añade esta línea
  provider: ^6.1.2
  dio: ^5.0.0
  path_provider: ^2.0.9
  pdf: ^3.11.1
  open_file: ^3.2.1
  file_picker: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/
    - assets/imagenes/fotos_mascotas/
