// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlAzj2tRvaywYJs_tnCWqvqUcNdjNxKt4',
    appId: '1:26968244961:web:6a99878bbaada9ca4eada0',
    messagingSenderId: '26968244961',
    projectId: 'homecoming-c3d02',
    authDomain: 'homecoming-c3d02.firebaseapp.com',
    storageBucket: 'homecoming-c3d02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pbRHQ1Sl2t9mfZftL0tfbObuCqWOoi8',
    appId: '1:26968244961:android:8b79c1d64f7a12ae4eada0',
    messagingSenderId: '26968244961',
    projectId: 'homecoming-c3d02',
    storageBucket: 'homecoming-c3d02.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWnvuJTXKd-fW30kfd8aFXni6GKA7-zCI',
    appId: '1:26968244961:ios:9d6798bf0724bf734eada0',
    messagingSenderId: '26968244961',
    projectId: 'homecoming-c3d02',
    storageBucket: 'homecoming-c3d02.appspot.com',
    iosBundleId: 'com.example.homecoming',
  );
}
